language: python
python:
  - '3.7.3'

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="trusty_monkey.settings"

services:
  - postgresql

script:
  -sudo ./trusty_monkey/manage.py test --keepdb