language: python
python:
  - '3.7.3'

sudo: required

before_install:
  - chmod +x gradlew
before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="trusty_monkey.settings"

services:
  - postgresql

script:
  - ./trusty_monkey/manage.py test --keepdb